/* =========================================================================
   FUTURE — CONTENT FILE  (edit this one file)
   -------------------------------------------------------------------------
   QUOTES      one flat list of lines. Every line shows signed "FUTURE".
               A line is a plain string, or { text: "..." }.
               These are original lines — replace with anything you have the
               right to use. (Song lyrics are copyrighted; your own writing,
               public-domain text, or licensed lines are safe.)

   BACKGROUNDS four backgrounds the user can pick from. Each has:
               bg     solid color (shown if no image)
               fg     text color on that background
               accent small highlight color
               image  optional photo slot — drop a file at this path and it
                      takes over automatically (e.g. images/bg-1.jpg).
                      Until a file exists, the solid color is used.
   ========================================================================= */

const QUOTES = [
   "She belongs to the streets",
  "Sensational",
  "Charge it to the game",
  "Be the problem",
  "It's a collection",
  "Casually pimpin'",
  "Freeband Taliban",
  "King of Toxic",
  "La Ferrari mentality",
  "I know I’m the last person you want to talk to but I still wanted to be the first to wish you a Happy Thanksgiving",
  "I promised you I could change I never promised you I would change",
  "Tell your brother I said LeBron is back on his game he'll know what it means lol Hope you're doing well",
  "I know you’ve probably washed your hands of me but I left some groceries on your grandmom’s porch Stay safe",
  "Hey I saw a cloud today that looked exactly like the dog we never got Thought of you",
  "I’m not texting you to get back together I’m just making sure you’re choosing peace even if it’s not with me",
  "I know you hate me right now but please don’t let my actions ruin the playlist I made for you",
  "Are you really happy or are you just trying to prove a point to me",
  "I see you’re doing big things now Just remember who taught you how to think big",
  "You can block my number but you can’t block the memories",
  "She got 100 dudes tryna be the solution stand out Be the problem",
  "Patience in a relationship is just waiting around to see if she has hotter friends",
  "If you love her let her go If she comes back she couldn't find anyone better Secure the win",
  "Never be the reason she cries Be the reason she has to keep her phone on Do Not Disturb",
  "Why be a king in her life when you can be the plot twist",
  "Love is just a word it don't matter to me",
  "Money and success bring me problems but I’m at my best when I’m running through drama",
  "Don't look for peace when you can be the storm they try to survive",
  "If she says she needs space give her the entire universe",
  "They say communication is key but silence keeps them guessing",
  "I despise you but I still want to buy you designer",
  "I'm doing good I'm doing great",
  "I’m a connoisseur of toxic situations",
  "I’m casually living my life don't let my happiness upset you",
  "I put you in that mansion but you still belong to the streets",
  "Best thing I ever did was choose myself over us",
  "I’m trying to forget about you but the bank account keeps growing",
  "My heart is cold but my wrist is colder",
  "I gave you a chance you gave them a story",
  "Sorry it didn't work out but my schedule just freed up",
  "I'm casually pimpin' these bitches I don't give a fuck if the bitch is Catholic",
  "Money and sex is bringin' me problems but I'm at my best when I'm runnin' through models",
  "Only fucking on her just to get to you only fucking on her cause I'm missing you",
  "I turn pain into diamonds",
  "I'm on the stage right now singing a toxic song",
  "They take my kindness for weakness still comin' out strong",
  "Best thing I ever did was move on to the next one",
  "I can't let hate determine my future",
  "I feel like I'm one of none",
  "I set the trend they just follow the blueprint",
  "If you miss me just say that Don't go posting old pictures of us from 2019",
  "I saw you deleted our playlist That's fine I already used those same songs for someone else",
  "I'm not trying to cause drama I just think your new man looks like he borrows money from his mom",
  "You can block me on everything but you're still gonna hear my voice every time you turn on the radio",
  "I didn't break your heart I just gave it back the way I found it",
  "I know I messed up but let's look at the bigger picture We both grew from this",
  "I'm not toxic I'm just honest about my options",
  "You said you wanted a mature guy but the moment I acted single you got mad",
  "I'm not checking your stories my friends just happen to send me everything you post",
  "I didn't change I just found out who I was when you weren't around",
  "You thought you were replacing me but you just found a downgrade with a better attitude",
  "I know you're asleep but I just wanted to tell you that the song we used to listen to just came on Goodnight",
  "Don't let a temporary argument ruin a permanent connection",
  "I may not be the one for you but I'm definitely the one you'll never forget",
  "I don't hurt feelings I just deliver realities",
  "I'm not hiding from my past I'm just running towards my commas",
  "Fck up the commas let's fck up some commas",
  "Where your ass was at dog you went and switched sides",
  "I'm turnin' up some more I done been too damn broke",
  "I was never snitching I can put it on the Bible",
  "I'm drinking lean they thought I died",
  "They passed us they doin' too much Haven't done my taxes I'm too turnt up",
  "She told me she loves me I told her I love the game more",
  "If she's too available she's not the one The streets need her back",
  "I left my watch at your place not because I forgot it but to remind you of the time you wasted",
  "I saw your new post Glad to see you're using the angles I taught you",
  "I know you told your therapist about me but did you tell them what you did to make me act like that",
  "I don't have an attitude I just have a high net worth and low tolerance",
  "You can't spell future without u and r but I'm doing just fine on my own",
  "I don't miss you I just miss the version of myself I was when I was flexing on you",
  "I told her I was busy but I was really just sitting in my car listening to my own verses",
  "She wanted commitment I gave her a luxury handbag Same difference",
  "If I ever said I love you just know the liquor was doing the talking",
  "I don't chase I replace",
  "You said I ruined your life but your credit score went up 100 points while we were together",
  "I didn't ghost you I just prioritized my peace over your paragraphs",
  "I saw you at the club Nice outfit looks like the one I bought your friend",
  "I'm dat nigga",
  "I know you're trying to move on but your new gym playlist is entirely my discography",
  "I don't hold grudges I just hold onto my options",
  "You cross my mind sometimes but then I remember my bank account and get distracted",
  "I'm not heartless I just learned how to use my heart less",
  "We didn't break up we just went on an indefinite hiatus from accountability",
  "I saw you out looking happy Good job on the acting skills",
  "I don't compete for spots I already owned",
  "You said I'm the problem but you keep coming back to solve it",
  "I never lied to you I just gave you the version of the truth you wanted to hear",
  "My text bubble might be green now but my money is still blue",
  "I don't look back unless it's to see how far ahead I am",
  "You hate me because I gave you exactly what you asked for just not how you expected it",
  "I'm not ignoring you I'm just letting my battery dictate our communication",
  "You said I changed but my bank account is the only thing that looks different",
  "I didn't break your promise I just renegotiated the terms",
  "If I made you cry just know it was a character building moment for you",
  "I didn't break your promise I just renegotiated the terms",
  "I can't be late if I never promised I was coming",
  "Your new man posts you every day because he's insecure I didn't post you because I'm humble",
  "I'm not playing games I'm just playing the field",
  "You told me to have a good life so I started flexing",
  "I saw you in my dreams last night Even in my sleep I was unbothered",
  "Don't call it a comeback call it a relapse into my old habits",
  "I don't need a valentine I need a wire transfer",
  "You thought you were a priority but you were just a premium option",
  "I didn't lose you the streets reclaimed what was theirs",
  "I might be the villain in your story but I'm the hero in mine",
  "I'm not heartless I'm just emotionally budgeted",
  "You can't ruin my day if I don't check my messages",
  "I know you miss me it’s only human",
  "I'm not text shy I'm just peace oriented",
  "You want closure I want commas",
  "I'm not toxic I'm just an acquired taste",
  "Never let an argument get in the way of a good outfit",
  "I saw your paragraph I'm happy for you or sorry that happened",
  "I don't block my exes I let them watch the success story",
  "You said I'm a red flag but red is my favorite color",
  "I didn't ruin your birthday I just made it unforgettable",
  "I'm not single I'm just on a solo world tour",
  "You love the idea of me and honestly so do I",
  "I'm not ignoring your advice I'm just trusting my own bad decisions",
  "I don't look back unless it's to check my posture",
  "You said you're doing better without me but you still check who viewed your story first",
  "I’m not checking up on you I’m just making sure my absence is being felt properly",
  "I know I’m hard to forget I left an impression and a couple of hoodies",
  "You wanted a gentleman but you fell in love with a rockstar",
  "I didn’t break your heart I just tested its durability",
  "My intentions weren't bad they were just poorly timed",
  "I’m not trying to compete with your past I’m just outrunning your future",
  "You say I’m emotionally unavailable but I’m always available for the bag",
  "I didn't mean to ghost you I just got distracted by my own potential",
  "You can't stay mad at me forever the playlist I made you is too good",
  "I'm not looking for a second chance I'm just making sure you remember the first one",
];

const _IMG = (typeof window !== "undefined" && window.SAID_BG_IMAGES) || {};
const BACKGROUNDS = [
  { id: "bg1", name: "Mirror", bg: "#242525", fg: "#FFFFFF", accent: "#FFFFFF", image: _IMG.bg1 || "images/bg-1.jpg" },
  { id: "bg2", name: "Eagle",  bg: "#1F1818", fg: "#FFFFFF", accent: "#FFFFFF", image: _IMG.bg2 || "images/bg-2.jpg" },
  { id: "bg3", name: "Hood",   bg: "#312D21", fg: "#FFFFFF", accent: "#FFFFFF", image: _IMG.bg3 || "images/bg-3.jpg" },
  { id: "bg4", name: "Chef",   bg: "#424242", fg: "#FFFFFF", accent: "#FFFFFF", image: _IMG.bg4 || "images/bg-4.jpg" }
];

const DEFAULT_BG = "bg1";

if (typeof window !== "undefined") {
  window.SAID_DATA = { QUOTES, BACKGROUNDS, DEFAULT_BG };
}
